- name: variables
  hosts: localhost
  vars: #declaring the variable or variable declaration
    Course: "Terraform"
    Trainer: "Siva"
    Duration: "15hrs"
  tasks:
  - name: print information
    ansible.builtin.debug:
     # msg: "Hi, We are learning Ansible from Trainer Sivakumar, Duration is 120hrs."
      msg: "Hi, We are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}."